# Generated by Django 5.1.3 on 2024-12-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('transmission', models.CharField(max_length=200)),
                ('engine_volume', models.CharField(max_length=2000)),
                ('drive', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('power_volume', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'cars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя заказчика')),
                ('number', models.CharField(max_length=12, unique=True, verbose_name='Номер телефона')),
                ('message', models.TextField(blank=True, verbose_name='текст обращения')),
                ('argee', models.BooleanField(default=True, verbose_name='согласен с условиями')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'db_table': 'contact',
                'managed': True,
            },
        ),
    ]
