# Generated by Django 5.1.3 on 2024-12-19 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_remove_contact_argee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. Максимально допустимое количество цифр - 15.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона'),
        ),
    ]
